### ISSUE TITLE
Contact us, nobody is around...

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/goinvo.com#106]
1. Banner image shows a deserted studio... doesn't feel like a ringing endorsement for reaching out to us... "hey, look, noone's home right now." :(
2. Padding is rather tight within the input fields across the site

<img width="1323" alt="screen shot 2018-10-16 at 10 34 30 am" src="https://user-images.githubusercontent.com/983918/47024145-250bd280-d12f-11e8-8ec4-82e19180cae5.png">

**Comment by jen-p** [comment]
2nd photoshoot: new team shot + one from above to put here

**Comment by ericbenwa** [comment]
Input field formatting is better now.
