### ISSUE TITLE
Use different photo

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com#133]
We already use this photo of SDOH quite a bit. Is there another image that represents our Opensource projects? This is on the About page.

<img width="1440" alt="screenshot 2018-10-17 14 44 28" src="https://user-images.githubusercontent.com/20907762/47109142-801af380-d21b-11e8-9b75-d1ecf2fce004.png">

**Comment by jen-p** [comment]
How is this?
![screen shot 2018-10-23 at 1 06 32 pm](https://user-images.githubusercontent.com/1414310/47377892-7fbfa400-d6c4-11e8-8bfc-a1f79f73105b.png)
