### ISSUE TITLE
Candidate Application right under the job description?

### ISSUE THREAD

**Issue by jsonin** [goinvo/goinvo.com#144]
https://www.goinvo.com/about/careers/

Especially on mobile, but even on desktop, the Application form is separated from the actual description. Should we put it inside the 'white letter' box of the description (under the text)?

**Comment by jen-p** [comment]
Maybe add a button

**Comment by ericbenwa** [comment]
Will be solved with this PR.
https://github.com/goinvo/goinvo.com/pull/350
