### ISSUE TITLE
DoH interactive is label-less on mobile.

### ISSUE THREAD

**Issue by jsonin** [goinvo/goinvo.com#145]
![image](https://user-images.githubusercontent.com/106187/47397472-66871980-d6fd-11e8-9e89-bba8c6a23abf.png)

Should we have labels under the icons (above the DoH pie chart)?

**Comment by craigmcginley** [comment]
This was by design per @jen-p and @edwinychoi. Labels didn't fit on mobile (previously the graph got super tiny to fit them on mobile).

**Comment by craigmcginley** [comment]
Perhaps if we trim up the padding below the graph the title of the category will be better seen? The other issue here is we're still missing the percentages (in numbers, obviously can be eye-balled on the graph)

**Comment by craigmcginley** [comment]
done in af04281b431d9d18ef448dcfe804a207ac48fa5f
