### ISSUE TITLE
Work page: save state, or return to category from case study

### ISSUE THREAD

**Issue by jen-p** [goinvo/goinvo.com#151]
On the Work page, is there any way that we can preserve state for the filter selections? For instance, if I pick “Precision Medicine and Genomics” and then click on the WuXi NextCODE case study, there’s no way for me to go to the other case studies in “Precision Medicine and Genomics” once I’m done reading it. And, if I back up, the filter is gone from the Work page. So, I have to select “Precision Medicine and Genomics” again to see the group of related case studies.

-Jon

**Comment by craigmcginley** [comment]
done in b8bf3ec66d7d178b75ecd3d6595aa8489c6d2ddc


Note: it doesn't work if you click on a feature from the old site and don't use browser back. Can't save state in the client at that point. Could use local storage but...? This seems okay for now.
