### ISSUE TITLE
Few more 404 errors occurring 

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/goinvo.com#154]
I'll keep checking every now and then to see if more trickle in... but here is the latest.

1.
https://www.goinvo.com/planting-seeds-and-tilling-soil/
to 
https://yes.goinvo.com/articles/planting-seeds-and-tilling-soil

2.
https://www.goinvo.com/the-internet-of-things-seeding-boston-start-ups-and-one-user-experience-for-all/
to
https://yes.goinvo.com/articles/the-internet-of-things-seeding-boston-start-ups-and-one-user-experience-for-all

3.
https://www.goinvo.com/baseball/
to
https://www.goinvo.com/

4.
https://www.goinvo.com/work/mcafee/
to
https://www.goinvo.com/

**Comment by craigmcginley** [comment]
added redirects in 619c0b8fc481fb4184e50276c3a6b086b88905ec
