### ISSUE TITLE
Fuzzy SDOH on home page

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com#16]
The animation looks just a little too blurry to me. Do you need me to make a higher quality version or is there anything else we can do to make this look crisp?

**Comment by sel2sm** [comment]
@craigmcginley do you think we'll be able to switch this with the much sharper animation? It's only slightly bigger. I think the crispness had been lost due to the way I originally made the project in After Effects and not because of how I exported, so once I fixed that, it became much clearer with little size increase.

**Comment by craigmcginley** [comment]
@sel2sm I tested switching for `sdoh_herov2_sm` and it looks a little better. We'll need a new poster image for that though cause the old one doesn't match up right. We can review in person.

**Comment by ericbenwa** [comment]
Closing as this image is not on the homepage anymore.
