### ISSUE TITLE
Add heatmap tracking in head

### ISSUE THREAD

**Issue by BrysonWong1** [goinvo/goinvo.com#179]
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:943265,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by craigmcginley** [comment]
@BrysonWong1 what does hotjar add for us with analytics? we already have hubspot + google. we can add more but ultimately we don't want to be bogged down with analytics scripts. what are our best options for consolidating?

**Comment by BrysonWong1** [comment]
Hi Craig, It adds some really helpful context, like heatmaps of where people's mouses go, how far they scroll and even recording of them using them using the site. If it's impacting speed maybe we keep it only for a month or two until after we make some tweaks.

**Comment by craigmcginley** [comment]
Does it overlap with (cover all functionality of) what we get with HubSpot/Google? Just wondering if we can narrow down. May not be a big deal.
