### ISSUE TITLE
Add Patricia Nguyen to About page

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/goinvo.com#198]
"Patricia Nguyen is a designer who works at the intersection of art and science to create beautiful and impactful healthcare software experiences. Born near Paris, she has lived in France and Canada. Patricia a graduate of McMaster University with a BS in Kinesiology, and has a Masters in Biomedical Communications from the University of Toronto."

(image in progress)

**Comment by PatriciaNguyen** [comment]
![995a0205-2](https://user-images.githubusercontent.com/46578977/50999108-71309e00-14f7-11e9-9a2c-d4ee046a0faa.jpg)

Edit: Patricia is *a* graduate of Mcmaster...
