### ISSUE TITLE
Bios... Farah, Colleen, Parsuree

### ISSUE THREAD

**Issue by jsonin** [goinvo/goinvo.com#243]
Since Farah has flown the coop back to grad school (good luck Farah!), her bio needs to come off.

Time to add Colleen.
Colleen's photo for the website:
https://www.dropbox.com/s/9e5026xhpepf2kw/colleen_poytang.jpg?dl=0
Colleen's website bio:
Colleen is a designer at the intersection of art and science. Her mission is to make healthcare and health information more accessible through beautiful storytelling. Colleen joined Invo in 2019 and has a BS in Psychology and Neuroscience from McMaster University and a MS in Biomedical Communication at the University of Toronto.

On Parsuree's bio:
"Parsuree joined Invo in 2018, and has a BA in Industrial Design from Chulalongkorn University and a MFA from Rochester Institute of Technology (RIT)."

(she's no longer a candidate MFA).

**Comment by craigmcginley** [comment]
Done in https://github.com/goinvo/goinvo.com/pulls?q=is%3Apr+is%3Aclosed
