### ISSUE TITLE
Remove Edwin from About page but keep bio on features

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/goinvo.com#257]
We also need to revise the `author.js` component to allow alumni bio's...?
Right now, if we remove Edwin from `team.js` it'll break/not show Edwin's bio on the features he has contributed to.

**Comment by ericbenwa** [comment]
Should we handle alumni + current all within the team.json?
But include a "flag" (ex. isAlumni) to detect if they are alumni and not include them on the team page?
Would this format be an improvement?

**Comment by jen-p** [comment]
Added alumni to author component, concatting it to team data, while migrating team member from team to alumni. In the future, we may want to retroactively add alumns who've contributed to features to the alumn json and reference the author component in the older features
