### ISSUE TITLE
COVID-19 comments from UserExperienceDesign Slack

### ISSUE THREAD

**Issue by jsonin** [goinvo/goinvo.com#274]
**What will the final product be? a website? Is this a mockup? Is this made for print? Keeping it as an image would be problematic for accessibility.
I’ve been very interested in the naming- how people refer to this virus. Once I heard that WHO gave it a name, I’ve been watching to see if the media outlets have changed what they call it. So far, I see and hear “coronavirus” much more in news headlines that COVID-19. I bring this up because in the early part of the page, it’s referred to as:  - the novel coronavirus, COVID-19, The 2019 Novel Coronavirus,  and  2019-nCov. This might be worth exploring, to help people become less confused.
The footnotes in the headings seem a little awkward, and a little confusing when you have number labels elsewhere. 
Will you have links to the separate sections listed at the top of the desktop view (I see they disappear in the smaller width view)?**

.... Juhan's Response:
The "final" thing, as of 915a ET today, is a visual "get to know Coronavirus" for those not in the scientific know (ie everyday residents of the US and elsewhere, that read less, read at a 5th grade level, and prefer a graphic novel/symbolic approach to storytelling). It will be a website and printable poster (in 2 form factors - long scroll and common entry wall-sized poster, two 80"x57" on top of each other).
It will be marked down to work on phones (ie css++). It's currently a heavy PDF. Ick.
We footnote everything, to be safe.
We'll have a more elegant footnoting technique once its in computable form. Then we'll also tune the contrast, text size, etc to meet with accessibility guidelines. The inserted comics = TBD.
We should have the sections jumpable on mobile. That's next week.
Good feedback.
....

**It took me a minute to figure out what the dark/light colors on the first graph meant. I saw after a bit that they aligned with the table below. Maybe callouts? On the timeline — could this be a map? Or also a map? It seems both spacial and time-related**

.... Juhan's Response:
Callouts = good idea. Will incorporate.
The timeline can be a map. I'll stick that into the backlog on GitHub.
....

**Hm, it's in english on a dot org but has tons of specific niché info only relevant to one country?**

.... Juhan's Response:
It's US centric... ish, correct. The action plans are based on US city protocols. We'll need to widen the aperture to feel more planetary, like we tried to do with UnderstandingEbola.org (which has a header bug as of this morning) + https://goinvo.com/features/ebola-care-guideline/files/ebola_care_guideline.pdf . I may need some help internationalizing.
....

**Agree on the naming - I know it’s scientific convention to call things ‘novel’ but it’s not common for the general populace to do so, and it’s blazed front and centre.
My major feedback would be to have more consistently plain language titles and navigation. This will help with both seo and readability. ‘What is Coronavirus?’ instead of ‘what is it?‘, “how is Coronavirus spread”, ‘’‘how to prevent coronavirus’ ‘what do I do if I think I have coronavirus’ ‘can I catch coronavirus from asian people (no, you idiots)’ ‘What you can do’ instead of ‘your part’ - ‘How the world is dealing with coronavirus’ instead of ‘action plan’ - that sort of thing. With the navigation, most of the words used don’t give anyone a reason to click, because they don’t give enough context.
Also in chrome I can’t seem to click on any of the navigation or footnotes**

.... Juhan's Response:
Naming brought up twice... we'll take your and Dorian's advice and adjust based on your suggestions. Thank you.
....

**In addition to the section where you compare COVID-19 with Sars and Mers, would it be interesting to also compare how these viruses spread over time, i.e. how long before SARS/MERS peaked? There’s data here: https://github.com/CSSEGISandData/COVID-19, updated daily.
Also, there was a recent Science Vs episode on the coronavirus, in which they compared the contagiousness of the flu, the coronavirus, and the measles. Never knew that “measles is bonkers contagious”**
https://gimletmedia.com/shows/science-vs/5whmvld/coronavirus-outbreak-how-scared-should

.... Juhan's Response:
The like-viruses comparison, from spread to dx to treatment = it's a natural evolution. I dig it.
Thanks mucho for the fast and good suggestions/crit.

I'll update GitHub, so you can see your suggestions live... and reply here when we've implemented them (most likely some will manifest in next week's update).
....

**Comment by jen-p** [comment]
Made changes reflecting 
- additional mediums
- naming conventions
- graph callouts
