### ISSUE TITLE
New homepage hero banner

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/goinvo.com#293]
Replace current hGraph banner on the homepage with the attached one here.

![critical-mass-hero](https://user-images.githubusercontent.com/983918/80130682-ff069000-8566-11ea-88e6-691ae93cb1cf.jpg)

**Comment by jsonin** [comment]
Ding Ding! Like this!

**Comment by craigmcginley** [comment]
done in #294 ... should we explore the effort of making this covid related?
