### ISSUE TITLE
In the Appendix, one of the sets of graphics are backwards

### ISSUE THREAD

**Issue by jonfollett** [goinvo/goinvo.com#377]
The statistics shown on the second to last graphic in the article are backwards. The graphic features two blue faces. It should be "Show Face: 70% Not Happy" and "No Face: 76% Not Happy". You'll see the paragraph above the graphic confirms this.

Regarding the finding itself, the facial information, in this instance, seemed to slightly counteract the body language in the infographic.

**Comment by ericbenwa** [comment]
Done and live.
https://github.com/goinvo/goinvo.com/pull/378
