### ISSUE TITLE
Update Beckett's name and picture

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com#389]
Beckett's name and picture needs to be updated on:
1. Care Plans(https://www.goinvo.com/features/careplans/) (author mention + picture at the bottom for “Want to work together”?)
2. Zika (https://www.goinvo.com/features/digital-healthcare/) (author mention)
3. We should also update our picture for Open Office Hours in the About(https://www.goinvo.com/about/). It’s super out of date anyways…

**Comment by ericbenwa** [comment]
https://github.com/goinvo/goinvo.com/pull/402
