### ISSUE TITLE
Canver Nav: Needs to include special authorship thank you (above author list)

### ISSUE THREAD

**Issue by jsonin** [goinvo/goinvo.com#468]
On https://goinvo.com/vision/national-cancer-navigation/, 
we need to add 2 people to a special author call-out:

**Grace Cordovano**, PhD (https://www.linkedin.com/in/gcordovano/)
Healthcare Navigating Solutionist & De-Frictionizer
and
**Wendi Cross**, Ph.D. (https://www.linkedin.com/in/wendi-cross-98153519/)
Professor of Psychiatry (Psychology) and Pediatrics at University of Rochester Medical Center

**Comment by craigmcginley** [comment]
addressed in #465
