### ISSUE TITLE
Update Vanessa's Bio in Loneliness Feature

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com#469]
Vanessa says that she refers people to the feature she wrote with us often [Loneliness Feature](https://www.goinvo.com/vision/loneliness-in-our-human-code/), and it would be so helpful if we could update her bio!

Could we update it to:
"Vanessa specializes in health systems and public health modeling, with an emphasis in socio-structural factors of disease. She has a Bachelor of Science in Public Policy with double minors in Business Economics and Global Health from the University of Southern California, and a Master of Public Health from the University of Washington. She currently works as an epidemiologist at the MITRE Corporation."

Thanks!

**Comment by jsonin** [comment]
Let's have a tie-back to when she wrote the piece, and signal that MITRE wasn't yet part of her life (at that time).

"Vanessa specializes in health systems and public health modeling, with an emphasis in disease prevention research. At the time of this paper (2018), she graduated from the University of Southern California with a B.S. in Public Policy and a double minor in Business Economics and Global Health. She has a Master's Degree in Public Health from the University of Washington and, as of 2020, works as an epidemiologist at the MITRE Corporation."

**Comment by craigmcginley** [comment]
addressed in #474
