### ISSUE TITLE
Adjust Virtual Diabetes Care Preview Image

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com#470]
The preview image for https://www.goinvo.com/vision/virtual-diabetes-care/ looks odd as it's not focused on the patient. 
If we could try out left aligning the preview or using a cropped version for the preview like this: https://www.dropbox.com/s/su9ysghz7kwf7ej/banner_v2_cropped.png?dl=0, that would be amazing!

**Comment by craigmcginley** [comment]
fixed in #475
