### ISSUE TITLE
Favicon gets blurry for old site

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com#89]
<img width="403" alt="screenshot 2018-10-15 22 03 52" src="https://user-images.githubusercontent.com/20907762/46988360-42588680-d0c6-11e8-8eb9-04bb7863f17b.png">

Super weird. The favicon is really pixelly for old website that we link to in the new website

**Comment by craigmcginley** [comment]
fixed at https://github.com/goinvo/goinvo.com-2018-old-features/commit/3893b86244f65b11e1187435e29f952ab01027f6
